language: node_js
node_js:
  - "6"
  - "8"
  - "10"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

sudo: false

before_install:
  - wget http://download.redis.io/releases/redis-4.0.8.tar.gz
  - tar xvzf redis-4.0.8.tar.gz
  - cd redis-4.0.8
  - make
  - sudo make install
  - cd ..
  - rm redis-4.0.8.tar.gz
